name: freezed_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.2
  freezed: ^0.12.1
  json_serializable: ^3.5.0
